uint8 TRANSITION_CONFIGURING = 10
uint8 TRANSITION_CLEANINGUP = 11
uint8 TRANSITION_SHUTTINGDOWN = 12
uint8 TRANSITION_ACTIVATING = 13
uint8 TRANSITION_DEACTIVATING = 14
uint8 TRANSITION_ERRORPROCESSING = 15

string node_name
uint8 transition
---
bool success
